# Generated by Django 4.0.4 on 2022-04-24 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('harvester', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(
                                   auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                   parent_link=True, primary_key=True, serialize=False, to='common.commoninfo')),
                ('reportTime', models.DateTimeField(blank=True, null=True)),
                ('report', models.JSONField(blank=True, null=True)),
                ('harvester', models.ForeignKey(
                              on_delete=django.db.models.deletion.CASCADE, related_name='errorharvester',
                              to='harvester.harvester')),
                ('location', models.ForeignKey(
                             on_delete=django.db.models.deletion.CASCADE, related_name='errorlocation',
                             to='location.location')),
            ],
            options={
                'abstract': False,
            },
            bases=('common.commoninfo',),
        ),
    ]
