# Generated by Django 4.0.4 on 2022-08-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('errorreport', '0003_errorreport_event'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='errorreport',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')
        )
    ]