# Generated by Django 4.0.4 on 2022-10-11 21:45

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('errorreport', '0004_auto_20220830_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreport',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
