# Generated by Django 4.0.4 on 2023-01-20 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0005_harvester_thingname_historicalharvester_thingname'),
        ('location', '0002_location_site_channel'),
        ('errorreport', '0007_auto_20221020_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='harvester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harvester.harvester'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
    ]
