# Generated by Django 4.0.4 on 2023-12-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_picksession_harvester_picksession_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='picksession',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
