# Generated by Django 4.0.4 on 2022-10-20 17:32
from django.core.paginator import Paginator
from django.db import migrations

import structlog

logger = structlog.get_logger(__name__)


def bugfix_mm_conversion(apps, schema_editor):
    EmuStatsReport = apps.get_model("emulatorstats", "emustatsreport")
    correction_factor = 10**6  ## Incorrectly divided m by 1000 to get mm
    paginator = Paginator(EmuStatsReport.objects.all(), 1000)
    for page in range(1, paginator.num_pages + 1):
        logger.info(f"Page {page}")
        for report in paginator.page(page).object_list:
            try:
                report.mm_traveled = report.mm_traveled * correction_factor
                report.save()
            except Exception:
                logger.error(f"Report {report.id} couldn't adjust mm_travelled")
                logger.error(f"{report.mm_travelled}")
                raise  # We want to abort this migrtion if it fails


class Migration(migrations.Migration):

    dependencies = [
        ("emulatorstats", "0001_initial"),
    ]

    operations = [migrations.RunPython(bugfix_mm_conversion)]
