# Generated by Django 4.1 on 2024-07-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emulatorstats", "0005_alter_emustatsreport_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="emustatsreport",
            name="drop_apples_rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
