services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    networks:
      - "hds-network"

  web:
    extends:
      file: docker-compose.base.yml
      service: web
    volumes:
      - ./hds/:/opt/app/hds
    environment:
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - USES3=${USES3}
      - JOB_SERVER_ADDRESS=${JOB_SERVER_ADDRESS}
      - GITHASH=${GITHASH:-"UNKNOWN"}
    ports:
      - ${HDS_PORT}:8000
    networks:
      - "hds-network"

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    networks:
      - "hds-network"

networks:
  hds-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.0.0/16
