services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - "hds-network"
  web:
    build: .
    command: ["/opt/app/wait-for-it.sh", "db:5432", "--", "/opt/app/start-server.sh", "${HDS_PORT}"]
    volumes:
      - ./fixtures:/opt/app/fixtures
    ports:
      - 127.0.0.1:${HDS_PORT}:${HDS_PORT}
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DEBUG=1
      - SECRET_KEY=dummy_key
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
    networks:
      - "hds-network"
networks:
  hds-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.0.1/16