services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - "hds-network"
  web:
    build: .
    command: supervisord
    volumes: 
      - ./hds/:/opt/app/hds
      - ./fixtures:/opt/app/fixtures
    ports:
      - 127.0.0.1:${HDS_PORT}:${HDS_PORT}
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DEBUG=1
      - SECRET_KEY=dummy_key
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DJANGO_SUPERUSER_USERNAME=afttest
      - DJANGO_SUPERUSER_email=aft@aft.aft
      - DJANGO_SUPERUSER_PASSWORD=aft
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_HOST=db
      - SQL_PORT=5432
      - HDS_ROOT=/opt/app/hds
      - HDS_PORT=${HDS_PORT}
    depends_on:
      - db
    networks:
      - "hds-network"
networks:
  hds-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.0.1/16
