# Generated by Django 4.0.4 on 2022-10-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="harvester",
            name="is_emulator",
            field=models.BooleanField(default=False),
        ),
    ]
