# Generated by Django 4.0.4 on 2022-10-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("harvdeploy", "0001_initial"),
        ("harvester", "0002_harvester_is_emulator"),
    ]

    operations = [
        migrations.AddField(
            model_name="harvester",
            name="release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="harvdeploy.harvestercoderelease",
            ),
        ),
    ]
