# Generated by Django 4.0.4 on 2022-10-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0004_historicalharvester'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvester',
            name='thingName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalharvester',
            name='thingName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
