# Generated by Django 4.0.4 on 2022-10-10 21:50

from django.db import migrations
from django.core.management import call_command

def populate_history(apps, schema_editor):
    call_command('populate_history', auto=True)
class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0004_historicalharvester'),
    ]

    operations = [
        migrations.RunPython(populate_history)
    ]
