# Generated by Django 4.0.4 on 2023-12-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0007_alter_fruit_name_alter_harvester_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fruit",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="harvester",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalharvester",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
    ]
