# Generated by Django 4.1 on 2023-02-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aftconfigs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configreport",
            options={"get_latest_by": "reportTime"},
        ),
    ]
