# Generated by Django 4.1 on 2024-10-05 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("harvester", "0009_harvesterswinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("lastModified", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("MESSAGE", "Message")],
                        max_length=10,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True,
                        choices=[("INFO", "Info"), ("WARNING", "Warning")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                ("channels", models.JSONField(blank=True, null=True)),
                ("s3event", models.JSONField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_creator_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "harvester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="harvester.harvester",
                    ),
                ),
                (
                    "modifiedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_modifiedby_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
