# Generated by Django 4.0.4 on 2022-07-21 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("errorreport", "0001_initial"),
        ("exceptions", "0002_aftexception"),
    ]

    operations = [
        migrations.AddField(
            model_name="aftexception",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="errorreport.errorreport",
            ),
        ),
    ]
