# Generated by Django 4.0.4 on 2022-10-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0006_aftexception_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftexception',
            name='handled',
            field=models.BooleanField(default=False),
        ),
    ]
