# Generated by Django 4.0.4 on 2022-10-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exceptions", "0007_aftexception_handled"),
    ]

    operations = [
        migrations.AddField(
            model_name="aftexceptioncode",
            name="operator_msg",
            field=models.CharField(
                default="Please cycle the harvester", max_length=255
            ),
        ),
    ]
