# Generated by Django 4.0.4 on 2023-01-18 19:21

import logging

from django.core.paginator import Paginator
from django.db import migrations, models

from exceptions.utils import sort_exceptions


def get_primary_errors(apps, schema_editor):
    ErrorReport = apps.get_model('errorreport', 'errorreport')
    paginator = Paginator(ErrorReport.objects.all(), 1000)

    for page in range(1, paginator.num_pages + 1):
        logging.info(f"Page {page}")
        for report in paginator.page(page).object_list:
            excs = sort_exceptions(report.exceptions.all())
            excs[0].primary = True
            excs[0].save()

class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0009_aftexceptioncodemanifest_aftexceptioncode_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftexception',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(get_primary_errors),
    ]
