# Generated by Django 4.0.4 on 2023-01-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("s3file", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="s3file",
            name="bucket",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="s3file",
            name="filetype",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="s3file",
            name="key",
            field=models.CharField(max_length=255),
        ),
    ]
