# Generated by Django 4.0.4 on 2023-01-11 18:43

import logging

from django.core.paginator import Paginator
from django.db import migrations

def update_file_key(apps, schema_editor):
    S3File = apps.get_model('s3file', 'S3File')
    paginator = Paginator(S3File.objects.all(), 1000)
    logging.info("Updating S3 File Table")
    for page in range(1, paginator.num_pages + 1):
        logging.info(f"Page {page}")
        for s3file in paginator.page(page).object_list:
            # FileField can take the key via django-storages,
            # no downloading and uploading necessary.
            # https://stackoverflow.com/questions/50609686/django-storages-s3-store-existing-file
            s3file.file = s3file.key
            s3file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('s3file', '0003_s3file_file'),
    ]

    operations = [
        migrations.RunPython(update_file_key),
    ]
