# Generated by Django 4.0.4 on 2023-01-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s3file', '0004_auto_20230111_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='s3file.s3file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
