# Generated by Django 4.0.4 on 2023-01-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logparser", "0003_create_s3files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logsession",
            name="zip_file",
        ),
    ]
