# Generated by Django 4.0 on 2024-06-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "logparser",
            "0008_alter_logfile_created_alter_logsession_created_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="logsession",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
