AWS_PROFILE = aft-dev
AWS_ACCOUNT_ID = 082346306812
HDS_URL = "https://hdsapi.devcloud.advanced.farm"
FRONTEND_URL = "https://hds.devcloud.advanced.farm"
NODE_ENV = production

include ../hdsfrontend.mk