#!/bin/bash

echo "Aliases - For your convenience!" && echo ""

echo "runserver"
echo "  Build and run the server"
echo "  Alias to docker compose up -d --build" && echo ""
echo "stopserver"
echo "  Stop server and remove container"
echo "  Alias to docker compose down -v" && echo "" 
echo "migrations"
echo "  Make migrations in django container. Alias to python manage.py makemigrations" && echo ""
echo "migrate"
echo "  Execute migrations in django container. Alias to python manage.py migrate" && echo ""
echo "createsuperuser"
echo "  Create superuser in django container. Alias to python manage.py createsuperuser" && echo ""
echo "manage"
echo "  Use django manage.py in django container, example usage: manage <manage command>" && echo ""
echo "dcexec"
echo "  Execute command django container, example usage: dcexec echo \$USER"
echo "  Alias to docker compose exec web" && echo ""
echo "dbexec"
echo "  Execute command postgres container, example usage: dcexec echo \$USER"
echo "  Alias to docker compose exec db" && echo ""
echo "setport <port>"
echo "  Change the port the development server will bind to" && echo ""
echo "HELP"
echo "  Show this help page" && echo ""
