# Generated by Django 4.0.4 on 2022-11-11 00:00

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('harvjobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresults',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
