# Generated by Django 4.0.4 on 2022-12-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvjobs", "0002_jobresults_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="jobstatus",
            field=models.CharField(
                choices=[
                    ("Success", "Success"),
                    ("Failed", "Fail"),
                    ("Pending", "Pending"),
                    ("Error", "Error"),
                    ("Failed and errors", "Failerror"),
                    ("Failed to send", "Unsent"),
                    ("canceled", "Canceled"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="jobstatus",
            field=models.CharField(
                choices=[
                    ("Success", "Success"),
                    ("Failed", "Fail"),
                    ("Pending", "Pending"),
                    ("Error", "Error"),
                    ("Failed and errors", "Failerror"),
                    ("Failed to send", "Unsent"),
                    ("canceled", "Canceled"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="jobhostresult",
            name="result",
            field=models.CharField(
                choices=[
                    ("Failed", "Fail"),
                    ("Success", "Success"),
                    ("Error", "Error"),
                    ("canceled", "Canceled"),
                ],
                max_length=30,
            ),
        ),
    ]
