# Generated by Django 4.1 on 2023-12-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvjobs", "0004_jobresults_harvester_jobresults_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobresults",
            name="reportTime",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
