# Generated by Django 4.0.4 on 2022-12-07 23:00

from django.db import migrations, models
from hds.roles import RoleChoices

KNOWN_USER_MAPPING = {
    "aft": RoleChoices.MANAGER,  # aft is admin but should still have a higher than support role
    "sqs": RoleChoices.SQS,
    "jenkins": RoleChoices.JENKINS,
    "James": RoleChoices.MANAGER,
    "erik": RoleChoices.MANAGER,
    "diego": RoleChoices.DEVELOPER,
    "roshan": RoleChoices.DEVELOPER,
    "ruben": RoleChoices.DEVELOPER,
}


def set_user_roles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("common", "UserProfile")

    for user in User.objects.all():
        username = user.username
        role = KNOWN_USER_MAPPING.get(username, RoleChoices.SUPPORT)
        if user.profile is None:
            profile = Profile.objects.create(creator=user, user=user)
            profile.role = role
            profile.save()
        else:
            user.profile.role = role
            user.profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("support", "Support"),
                    ("developer", "Developer"),
                    ("manager", "Manager"),
                    ("sqs", "Sqs"),
                    ("jenkins", "Jenkins"),
                ],
                default="support",
                max_length=31,
            ),
        ),
        migrations.RunPython(set_user_roles),
    ]
