# Generated by Django 4.0.4 on 2022-10-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="site_channel",
            field=models.CharField(default="harvs-dev", max_length=40),
        ),
    ]
